name: fruit_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/app_icon.png"
  min_sdk_android: 21
