name: fruit_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
      sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  dots_indicator: ^4.0.1
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/app_icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils
  filename: app_image.dart
flutter_intl:
  enabled: true
